listen: :5409
debug: true
instagramDebug: true
userURLTemplate: "http://localhost:3004/qor/users/%v"

rpc:
  core: core:3005

db:
  debug:    true
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres
  
nats:
  url: nats://nats:4222
  stanCluster: stan
  stanID: accountstore1
