debug: true
channelport: 8081

api:
  core: core:3005
  auth: auth:8433
  chat: chat:2010
  sms:  sms:12326
  coins: trendcoin:2014
  checker: checker:2013
  payments: payments:7777
  accountstore: accountstore:5409

marketSMS: "Your ad could be here"

redis:
  addr: redis:6379

nats:
  url: nats://nats:4222

mail:
  username: 'testo'
  password: 'pass'
  host: 'mailcatcher'
  sender: 'dev@trendever.com'
  port: 25

elastic:
  debug: true
  trace: true
  addr: http://elastic:9200

paymentsRedirects:
  trendever: http://localhost:3002/chat/%v/payed/%v
