debug: true
channelport: 8081
coreaddr: core:3005
authaddr: auth:8433
chataddr: chat:2010
smsaddr:  sms:12326
natsURL: "nats://nats:4222"

marketSMS: "Your ad could be here"

redis:
  addr: redis:6379

mail:
  username: 'testo'
  password: 'pass'
  host: 'mailcatcher'
  sender: 'dev@trendever.com'
  port: 25

elastic:
  debug: true
  trace: true
  addr: http://elastic:9200
