debug: true
channelport: 8081
coreaddr: core:3005
authaddr: auth:8433
chataddr: chat:2010
smsaddr:  sms:12326
coinsaddr: trendcoin:2014
checkeraddr: checker:2013
paymentsaddr: payments:7777

marketSMS: "Your ad could be here"

redis:
  addr: redis:6379

nats:
  url: nats://nats:4222

mail:
  username: 'testo'
  password: 'pass'
  host: 'mailcatcher'
  sender: 'dev@trendever.com'
  port: 25

elastic:
  debug: true
  trace: true
  addr: http://elastic:9200
