port: "8433"
core_server: "core:3005"
sms_server: "sms:12326"
natsURL: nats://nats:4222
key: "asdasdasdasdasdasd"
password_len: 4
site_url: "http://localdev.trendever.com:3002/"
sms_template: "Введите код {{.Password}}"
debug: true
db:
    debug:    true
    user:     postgres
    password: 1234
    host:     db
    port:     5432
    base:     postgres
