debug: true
rpc: :2013
mandibleURL: http://images:8080/

lastCheckedFile: checker.last

db:
  debug:    true
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres

requestsPerTick: 10
minimalTickLen:  10000
pool:
  timeoutMin: 500
  timeoutMax: 2000
  reloginTimeout: 10000
users:
- name: nmstrs1
  pass: pass4ig
