debug: true
appHost: :3004
siteURL: http://localhost
mandibleURL: http://mandible:8089/

nats:
  url: nats://nats:4222
  stanCluster: stan
  stanID: core1

rpc:
  listen: :3005
  mail: mail:12325
  sms: sms:12326
  chat: chat:2010
  auth: auth:8433
  push: push:2011
  checker: checker:2013
  trendcoin: trendcoin:2014
  payments: payments:7777

db:
  debug:    true
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres
  
URL:
  monetization: http://localhost:3001/monetization
  connectBot:   http://localhost:3001/connect-bot

monetization:
  initialPlanName: init
  plansBaseDuration: 1m
  subscriptionCheckTick: 20s

comments:
  allowed: "цена,цвет,размер,стоимость"

bitly:
  login: o_v1v8rptir
  apiKey: R_05e4113d379c43d695030ba8fbac6edf
  accessToken: c8d0210ba7542be997bc36071d966e582ca9890b

