natsURL: nats://nats:4222
delay: 3000
debug: true
chunkSize: 2000

db:
  debug:    false
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres

elastic:
  debug: true
  addr: http://elastic:9200
