debug: true

rpc: 0.0.0.0:3006

db:
  debug:    false
  user:     postgres
  password: 1234
  host:     db
  port:     5432
  base:     postgres

nats:
  url: nats://nats:4222
  stanCluster: stan
  stanID: fetcher1

instagram:
  storeAddr: accountstore:5409
  timeoutMin: 3s
  timeoutMax: 5s
  responseLogging: false
  indentLogging: false
