debug: true

rpc: :3009

coreServer: core:3005
fetcherServer: fetcher:3006
productUrlFormat: 'https://localhost:8040/product/%d'
mandibleURL: 'http://mandible:8089/'
lastCheckedFile: 'savetrend.last'

instagram:
  timeoutMin: 500
  timeoutMax: 2000
  reloginTimeout: 10000
  pollTimeout: 10000
  users:
  - username: nmstrs1
    password: pass4ig
  trendUser: nmstrs1
