debug: true
token: '202642129:AAEQ2Dg-n_daCiSWqQwtlNjDFfIbAPmDgQU'
rpc:   ':4040'
rooms: 
  - name: 'new_user'
    room: '@trendever_debug'
  - name: 'new_lead'
    room: '@trendever_debug'
  - name: 'new_product'
    room: '@trendever_debug'
  - name: 'new_sms'
    room: '@trendever_debug'
  - name: 'accountstore'
    room: '@trendever_debug'
