debug: true

coreServer:      core:3005
fetcherServer:   fetcher:3006
saveTrendServer: savetrend:3009
orderUrlFormat:  'https://localhost:8040/order/%v'
mandibleURL:     'http://images:8080/'
lastCheckedFile: 'wantit.last'

instagram:
  timeoutMin: 500
  timeoutMax: 2000
  reloginTimeout: 10000
  pollTimeout: 10000
  users:
    - username: nmstrs2
      password: pass4ig
  wantitUser: nmstrs2
